### ISSUE TITLE
你太厉害了，必须夸赞

### ISSUE THREAD

**Issue by basicbh** [Circuitandbzgty/youkuvideo_ykv_unpacker#1]
成功转为ts文件，虽然不是很完美，但已经很厉害了
Extracted: 235.ts
Extracted: youku.m3u8
Traceback (most recent call last):
  File "e:\YKV\ykv_unpacker.py", line 54, in <module>
    main()
  File "e:\YKV\ykv_unpacker.py", line 51, in main
    unpack_files(file_path, output_folder)
  File "e:\YKV\ykv_unpacker.py", line 30, in unpack_files
    offset = file_info['offset']
             ~~~~~~~~~^^^^^^^^^^
KeyError: 'offset'
PS C:\Users\Administrator> 


然后m3u8的内容是，这个目录我不知道怎么生成的D:/Youku Files/download/XMTAzNTM3OTg4/，别人发给我的ykv文件
D:/Youku Files/download/XMTAzNTM3OTg4/1.ts
#EXTINF:10.12
#EXT-X-PRIVINF:FILESIZE=1732078
D:/Youku Files/download/XMTAzNTM3OTg4/2.ts
#EXTINF:13.2
#EXT-X-PRIVINF:FILESIZE=1688462
D:/Youku Files/download/XMTAzNTM3OTg4/3.ts
#EXTINF:13.04
#EXT-X-PRIVINF:FILESIZE=1480910
D:/Youku Files/download/XMTAzNTM3OTg4/4.ts
#EXTINF:11.32
#EXT-X-PRIVINF:FILESIZE=1595402
D:/Youku Files/download/XMTAzNTM3OTg4/5.ts

**Comment by basicbh** [comment]
补充：有些ykv文件转为ts后，ts文件无法播放，想必是加密了吧。。比如  新生 春花焰 等

**Comment by Circuitandbzgty** [comment]
> 补充：有些ykv文件转为ts后，ts文件无法播放，想必是加密了吧。。比如 新生 春花焰 等

独播剧集加密了，解不开的，需要密钥。这个工具不适用于解密独播剧集和电视剧。

**Comment by basicbh** [comment]
谢谢，已经很够用了
